name: Deploy api server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy laravel to vps
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Navigasi ke direktori proyek Laravel
            cd /var/www/pemira-api

            # Tarik perubahan terbaru dari Git
            git pull origin main

            # Instal dependensi Composer
            composer install --no-interaction --prefer-dist

            # Clear cache
            php artisan config:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
