name: Laravel CI/CD with GitHub Actions to Shared Hosting

on:
  push:
    branches:
      - main # Hanya berjalan saat ada perubahan di branch main.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1" # Sesuaikan dengan versi PHP di hosting Anda.
          extensions: mbstring, bcmath, xml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # Store the SSH private key in the correct location
          cat ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Secure the private key with proper permissions
          # Menambahkan server ke known_hosts untuk menghindari prompt
          ssh-keyscan -p 65002 153.92.11.126 >> ~/.ssh/known_hosts  # Ganti dengan alamat server Anda.

      - name: Deploy to Shared Hosting
        run: |
          ssh -p 65002 -o StrictHostKeyChecking=no u531289105@153.92.11.126 "
            cd /home/u531289105/public_html &&
            git pull origin main &&
            composer install --no-interaction --prefer-dist &&
            php artisan migrate --force &&
            php artisan config:cache &&
            php artisan route:cache &&
            php artisan storage:link
          "
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
